extends RefCounted

# ---------------------------------------------------
# ドット絵：建物のタイル（1マス = 16×16ドット）を文字で描き、起動時に画像にする。
# 1文字 = 1ドット。文字と色の対応は PALETTE、"." は透明。
# 横に何マスかにまたがる建物は、横幅 16×マス数 の絵として描く（例: オフィスは4マス = 64ドット）。
# 縦に何階分かの高さがある建物は、縦 16×階数 の絵として描く（例: 2階分の吹き抜けロビー = 32ドット）。
# 画像ファイルを用意しなくても、ここを書き換えるだけで見た目を変えられる。
# ---------------------------------------------------

const SIZE := 16

const PALETTE := {
	"K": Color("#1b1b24"), # 輪郭・天井と床の線
	"F": Color("#3a3a44"), # 床
	"G": Color("#5a5e68"), # 暗い灰色（エレベーターの床・警備室の机）
	"g": Color("#b8b8ae"), # 明るい灰色（階段室の壁・ベッドの脚）
	"W": Color("#a9bdd0"), # オフィスの壁
	"B": Color("#50607a"), # 窓枠
	"w": Color("#cfe8ff"), # 窓ガラス
	"v": Color("#ffffff"), # 窓の光
	"D": Color("#8a5a34"), # 机
	"d": Color("#5e3b20"), # 机の脚
	"M": Color("#2b2f3a"), # パソコン
	"m": Color("#6fd3ff"), # 画面
	"C": Color("#384a8a"), # 椅子
	"S": Color("#e0c080"), # 階段の踏み面
	"s": Color("#9c7a48"), # 階段の側面
	"R": Color("#6b6f7a"), # 手すり・レール
	"r": Color("#3e424c"), # シャフトの壁
	"c": Color("#9aa0aa"), # ケーブル
	"H": Color("#b59ad6"), # 客室の壁
	"U": Color("#8c5a9c"), # カーテン
	"P": Color("#f4f1ea"), # シーツ・タオル
	"E": Color("#7d4fb3"), # 掛け布団
	"e": Color("#6a4428"), # 木の家具
	"L": Color("#ffd966"), # 黄色（ランプ・チーズ）
	"T": Color("#79b8b4"), # ハウスキーパー室の壁
	"Y": Color("#e0b030"), # バケツ
	"O": Color("#8a6a40"), # モップの柄
	"N": Color("#f0b070"), # 飲食店の壁
	"n": Color("#a04a20"), # カウンター
	"Q": Color("#d99a3a"), # ハンバーガーのパン
	"q": Color("#6a3a1a"), # ハンバーガーの肉
	"Z": Color("#8d9a6a"), # ゴミ処理場の壁
	"z": Color("#3f8a3f"), # 緑のゴミ箱
	"x": Color("#3a5a8a"), # 青のゴミ箱
	"A": Color("#5a6aa0"), # 警備室の壁
	"a": Color("#f2c230"), # 警備のバッジ
	"V": Color("#e8eef2"), # メディカルセンターの壁
	"X": Color("#d83a3a"), # 赤十字
	"h": Color("#a6cf9a"), # 住宅の壁
	"o": Color("#7a4a2a"), # ドア
	"p": Color("#3c9a4a"), # 観葉植物
	"y": Color("#c0504d"), # ソファ
	"J": Color("#d8c08a"), # スイートの壁
	"j": Color("#8a2a3a"), # スイートの掛け布団・イベントホールの壁
	"I": Color("#f7a8c0"), # 結婚式場の花・バージンロード
}

const TILES := {
	"office": [
		"KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK",
		"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWB",
		"WWWWWWWWWWWWWWWWWBBBBBBWWBBBBBBWWBBBBBBWWBBBBBBWWBBBBBBWWBBBBBBB",
		"WWKKKKKKKWWWWWWWWBwwwvBWWBwwwvBWWBwwwvBWWBwwwvBWWBwwwvBWWBwwwvBB",
		"WWKaaaaaKWWWWWWWWBwwvwBWWBwwvwBWWBwwvwBWWBwwvwBWWBwwvwBWWBwwvwBB",
		"WWKKKKKKKWWWWWWWWBwwwwBWWBwwwwBWWBwwwwBWWBwwwwBWWBwwwwBWWBwwwwBB",
		"WWWWWWWWWWWWWWWWWBBBBBBWWBBBBBBWWBBBBBBWWBBBBBBWWBBBBBBWWBBBBBBB",
		"WWBBBBBWWWWWWppWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWB",
		"WWBoooBWWWWWppppWWWMMMMWWWWWWWWWWWWMMMMWWWWWWWWWWWWMMMMWWWWWWWWB",
		"WWBoooBWWWWWWppWWWWMmmMWWWWCCCWWWWWMmmMWWWWCCCWWWWWMvvMWWWWCCCWB",
		"WWBoooBWWWWWWOWWWWWMMMMWWWWCCCWWWWWMMMMPPWWCCCWWWWWMMMMWWWWCCCWB",
		"WWBoaoBWWWWWWOWWWDDDDDDDDWWWCWWWWDDDDDDDDWWWCWWWWDDDDDDDDWWWCWWB",
		"WWBoooBWWWWWeeeWWdWWWWWWdWWCCCWWWdWWWWWWdWWCCCWWWdWWWWWWdWWCCCWB",
		"WWBoooBWWWWWWeWWWdWWWWWWdWWCWCWWWdWWWWWWdWWCWCWWWdWWWWWWdWWCWCWB",
		"FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
		"KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK",
	],
	"stairs": [
		"KKKKKKKKKKKKKKKK",
		"ggggggggggRRggss",
		"ggggggggggggSSss",
		"ggggggggRRggssss",
		"ggggggggggSSssss",
		"ggggggRRggssssss",
		"ggggggggSSssssss",
		"ggggRRggssssssss",
		"ggggggSSssssssss",
		"ggRRggssssssssss",
		"ggggSSssssssssss",
		"RRggssssssssssss",
		"ggSSssssssssssss",
		"ggssssssssssssss",
		"FFFFFFFFFFFFFFFF",
		"KKKKKKKKKKKKKKKK",
	],
	"elevator": [
		"KKKKKKKKKKKKKKKK",
		"rrRrrrrccrrrrRrr",
		"rrRrrrrccrrrrRrr",
		"rrRrrrrccrrrrRrr",
		"rrRrrrrccrrrrRrr",
		"rrRrrrrccrrrrRrr",
		"rrRrrrrccrrrrRrr",
		"rrRrrrrccrrrrRrr",
		"rrRrrrrccrrrrRrr",
		"rrRrrrrccrrrrRrr",
		"rrRrrrrccrrrrRrr",
		"rrRrrrrccrrrrRrr",
		"rrRrrrrccrrrrRrr",
		"rrRrrrrccrrrrRrr",
		"GGGGGGGGGGGGGGGG",
		"KKKKKKKKKKKKKKKK",
	],
	"express_elevator": [
		"KKKKKKKKKKKKKKKK",
		"nrYrrrrccrrrrYrn",
		"nrYrrrrccrrrrYrn",
		"nrYrrrrccrrrrYrn",
		"nrYrrrrccrrrrYrn",
		"nrYrrrrccrrrrYrn",
		"nrYrrrrccrrrrYrn",
		"nrYrrrrccrrrrYrn",
		"nrYrrrrccrrrrYrn",
		"nrYrrrrccrrrrYrn",
		"nrYrrrrccrrrrYrn",
		"nrYrrrrccrrrrYrn",
		"nrYrrrrccrrrrYrn",
		"nrYrrrrccrrrrYrn",
		"GGGGGGGGGGGGGGGG",
		"KKKKKKKKKKKKKKKK",
	],
	"hotel": [
		"KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK",
		"HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH",
		"HHHBBBBBBBBBBHHHHHHBBBBBBBBBBHHH",
		"HHUBwwwwwwwwBUHHHHUBwwwwwwwwBUHH",
		"HHUBwwwvwwwwBUHHHHUBwwwvwwwwBUHH",
		"HHUBwwwwwwwwBUHHHHUBwwwwwwwwBUHH",
		"HHUBBBBBBBBBBUHHHHUBBBBBBBBBBUHH",
		"HHUHHHHHHHHHHUHHHHUHHHHHHHHHHUHH",
		"HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH",
		"HHLHHHHHHHHHHHHHHHHHHHHHHHHHHHHH",
		"HLLLHHHHHHHHHHHHePPPEEEEEEEEEEeH",
		"HHeHHHHHHHHHHHHHePPPEEEEEEEEEEeH",
		"HeeeHHHHHHHHHHHHeeeeeeeeeeeeeeeH",
		"HeHeHHHHHHHHHHHHeHHHHHHHHHHHHHeH",
		"FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
		"KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK",
	],
	"hotel_twin": [
		"KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK",
		"HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH",
		"HHHBBBBBBBBBBHHHHHHBBBBBBBBBBHHHHHHBBBBBBBBBBHHH",
		"HHUBwwwwwwwwBUHHHHUBwwwwwwwwBUHHHHUBwwwwwwwwBUHH",
		"HHUBwwwvwwwwBUHHHHUBwwwvwwwwBUHHHHUBwwwvwwwwBUHH",
		"HHUBwwwwwwwwBUHHHHUBwwwwwwwwBUHHHHUBwwwwwwwwBUHH",
		"HHUBBBBBBBBBBUHHHHUBBBBBBBBBBUHHHHUBBBBBBBBBBUHH",
		"HHUHHHHHHHHHHUHHHHUHHHHHHHHHHUHHHHUHHHHHHHHHHUHH",
		"HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH",
		"HHLHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH",
		"HLLLHHHHHHHHHHHHePPPEEEEEEEEEEeHePPPEEEEEEEEEEeH",
		"HHeHHHHHHHHHHHHHePPPEEEEEEEEEEeHePPPEEEEEEEEEEeH",
		"HeeeHHHHHHHHHHHHeeeeeeeeeeeeeeeHeeeeeeeeeeeeeeeH",
		"HeHeHHHHHHHHHHHHeHHHHHHHHHHHHHeHeHHHHHHHHHHHHHeH",
		"FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
		"KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK",
	],
	"hotel_suite": [
		"KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK",
		"JJJJJJJLLJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJLLJJJJJJJJJJJJJJJJJJJJJJJ",
		"JJJBBBBBBBBBBJJJJJJBBBBBBBBBBJJJJJJBBBBBBBBBBJJJJJJBBBBBBBBBBJJJ",
		"JJUBwwwwwwwwBUJJJJUBwwwwwwwwBUJJJJUBwwwwwwwwBUJJJJUBwwwwwwwwBUJJ",
		"JJUBwwwvwwwwBUJJJJUBwwwvwwwwBUJJJJUBwwwvwwwwBUJJJJUBwwwvwwwwBUJJ",
		"JJUBwwwwwwwwBUJJJJUBwwwwwwwwBUJJJJUBwwwwwwwwBUJJJJUBwwwwwwwwBUJJ",
		"JJUBBBBBBBBBBUJJJJUBBBBBBBBBBUJJJJUBBBBBBBBBBUJJJJUBBBBBBBBBBUJJ",
		"JJUJJJJJJJJJJUJJJJUJJJJJJJJJJUJJJJUJJJJJJJJJJUJJJJUJJJJJJJJJJUJJ",
		"JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ",
		"JJJJJJJJJJJJJJJJJJLJJJJJJJJJJJJJeJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJe",
		"JyyyyyyyyyyyyyyJJLLLJJJJJJJJJJJJePPPPPjjjjjjjjjjjjjjjjjjjjjjjjje",
		"yyyyyyyyyyyyyyyyJJeJJJJJJJJJJJJJePPPPPjjjjjjjjjjjjjjjjjjjjjjjjje",
		"yJJJJJJJJJJJJJJyJeeeJJJJJJJJJJJJeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee",
		"JJJJJJJJJJJJJJJJJeJeJJJJJJJJJJJJeJJJJJJJJJJJJJJeeJJJJJJJJJJJJJJe",
		"FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
		"KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK",
	],
	"wedding": [
		"KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK",
		"VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV",
		"VVVVVVVVVVVVVVVVVVVBBBBBBBBBBVVVVVVBBBBBBBBBBVVVVVVBBBBBBBBBBVVVVVVBBBBBBBBBBVVVVVVVVVLLLLVVVVVV",
		"VVVVVVIVVVVVVVVVVVVBwwwwwwwwBVVVVVVBwwwwwwwwBVVVVVVBwwwwwwwwBVVVVVVBwwwwwwwwBVVVVVVVVLLVVLLVVVVV",
		"VVVVVIpIVVVVVVVVVVVBwwwwvwwwBVVVVVVBwwwwvwwwBVVVVVVBwwwwvwwwBVVVVVVBwwwwvwwwBVVVVVVVVLVVVVLVVVVV",
		"VVVVVVpVVVVVVVVVVVVBwwwwwwwwBVVVVVVBwwwwwwwwBVVVVVVBwwwwwwwwBVVVVVVBwwwwwwwwBVVVVVVVLVVIIVVLVVVV",
		"VVVIVVpVVVIVVVVVVVVBBBBBBBBBBVVVVVVBBBBBBBBBBVVVVVVBBBBBBBBBBVVVVVVBBBBBBBBBBVVVVVVVLVIIIIVLVVVV",
		"VVIpIVpVVIpIVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVIVVLVVIIVVLVVIV",
		"VVVpVVpVVVpVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVIpIVLVVVVVVLVIpI",
		"VVVpVepeVVpVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVpVVLVVVVVVLVVpV",
		"VVVpVeeeVVpVVVVVeeeeeeVVVVeeeeeeeeeeeeVVVVeeeeeeeeeeeeVVVVeeeeeeeeeeeeVVVVeeeeeeVpVVLVVVVVVLVVpV",
		"VeeeeeeeeeeeeeVVeVVVVeVVVVeVVVVeeVVVVeVVVVeVVVVeeVVVVeVVVVeVVVVeeVVVVeVVVVeVVVVeVpVVLVVVVVVLVVpV",
		"VeVVVVVVVVVVVeVVeeeeeeIIIIeeeeeeeeeeeeIIIIeeeeeeeeeeeeIIIIeeeeeeeeeeeeIIIIeeeeeeIIIIIIIIIIIIVeee",
		"VeVVVVVVVVVVVeVVeVVVVeIIIIeVVVVeeVVVVeIIIIeVVVVeeVVVVeIIIIeVVVVeeVVVVeIIIIeVVVVeIIIIIIIIIIIIVeVe",
		"FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
		"KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK",
	],
	"event_hall": [
		"KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK",
		"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
		"jjLjjjjjjjjjjjjjjjjjjjjLjjjjjjjjjjjjjjjLjjjjjjjjjjjjjjjLjjjjjjjjjjjjjjjLjjjjjjjjjjjjjjjjjjjjjLjj",
		"jUUUUUUGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGUUUUUUj",
		"jUUUUUGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGLLLGGGGGGGGGGGGGLLLGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGUUUUUj",
		"jUUUUUGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGLLLLLGGGGGGGGGGGLLLLLGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGUUUUUj",
		"jUUUUGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGLLLGGGGGGGGGGGGGLLLGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGUUUUj",
		"jUUUUGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGLGGGGGGGGGGGGGGGLGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGUUUUj",
		"jUUUGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGLGLGGGGGGGGGGGGGLGLGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGUUUj",
		"jUUUeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeUUUj",
		"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
		"yyjyyjyyjyyjyyjyyyjyyjyyjyyjyyjyyyjyyjyyjyyjyyjyyyjyyjyyjyyjyyjyyyjyyjyyjyyjyyjyyjyyjyyjyyjyyjyy",
		"yyjyyjyyjyyjyyjyyyjyyjyyjyyjyyjyyyjyyjyyjyyjyyjyyyjyyjyyjyyjyyjyyyjyyjyyjyyjyyjyyjyyjyyjyyjyyjyy",
		"ejjejjejjejjejjeejjejjejjejjejjeejjejjejjejjejjeejjejjejjejjejjeejjejjejjejjejjeejjejjejjejjejje",
		"FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
		"KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK",
	],
	"subway": [
		"KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK",
		"rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr",
		"rrrrwwwwwwwwrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr",
		"rrrrBvBvBvBvrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr",
		"rRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRr",
		"RggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggR",
		"RgwwwgwwgwwgwwgggwwgwwgwwgwwgwwggwwgwwgwwgwwgwwgggwwgwwgwwgwwwgR",
		"RgwwwgwwgwwgwwgggwwgwwgwwgwwgwwggwwgwwgwwgwwgwwgggwwgwwgwwgwwwgR",
		"RggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggR",
		"RxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxR",
		"RggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggR",
		"KKGGKKKKKKKKGGKKKKGGKKKKKKKKGGKKKKGGKKKKKKKKGGKKKKGGKKKKKKKKGGKK",
		"LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL",
		"GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
		"FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
		"KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK",
	],
	"lobby": [
		"KKKKKKKKKKKKKKKK",
		"ggVVVVVVVVVVVVgg",
		"ggVVVVVLLVVVVVgg",
		"ggVBBBBBBBBBBVgg",
		"ggVBwwwwwwwwBVgg",
		"ggVBwwvwwwwwBVgg",
		"ggVBwwwwwwwwBVgg",
		"ggVBwwwwwwwwBVgg",
		"ggVBwwwwwwvwBVgg",
		"ggVBwwwwwwwwBVgg",
		"ggVBBBBBBBBBBVgg",
		"ggVVVVVVVVVVVVgg",
		"VgVgVgVgVgVgVgVg",
		"gVgVgVgVgVgVgVgV",
		"FFFFFFFFFFFFFFFF",
		"KKKKKKKKKKKKKKKK",
	],
	"lobby2": [
		"KKKKKKKKKKKKKKKK",
		"ggVVVVVVVVVVVVgg",
		"ggVVVVVLLVVVVVgg",
		"ggVVVVLLLLVVVVgg",
		"ggVVVVVLLVVVVVgg",
		"ggVBBBBBBBBBBVgg",
		"ggVBwwwwwwwwBVgg",
		"ggVBwwwwwwwwBVgg",
		"ggVBwwvwwwwwBVgg",
		"ggVBwwwwwwwwBVgg",
		"ggVBwwwwwwwwBVgg",
		"ggVBwwwwwwvwBVgg",
		"ggVBwwwwwwwwBVgg",
		"ggVBwwwwwwwwBVgg",
		"ggVBwwwwwwwwBVgg",
		"ggVBwwvwwwwwBVgg",
		"ggVBwwwwwwwwBVgg",
		"ggVBwwwwwwwwBVgg",
		"ggVBwwwwwwvwBVgg",
		"ggVBwwwwwwwwBVgg",
		"ggVBwwwwwwwwBVgg",
		"ggVBwwwwwwwwBVgg",
		"ggVBwwvwwwwwBVgg",
		"ggVBwwwwwwwwBVgg",
		"ggVBwwwwwwwwBVgg",
		"ggVBwwwwwwvwBVgg",
		"ggVBwwwwwwwwBVgg",
		"ggVBBBBBBBBBBVgg",
		"VgVgVgVgVgVgVgVg",
		"gVgVgVgVgVgVgVgV",
		"FFFFFFFFFFFFFFFF",
		"KKKKKKKKKKKKKKKK",
	],
	"lobby3": [
		"KKKKKKKKKKKKKKKK",
		"ggVVVVVVVVVVVVgg",
		"ggVVVVVLLVVVVVgg",
		"ggVVVVLLLLVVVVgg",
		"ggVVVVVLLVVVVVgg",
		"ggVBBBBBBBBBBVgg",
		"ggVBwwwwwwwwBVgg",
		"ggVBwwwwwwwwBVgg",
		"ggVBwwvwwwwwBVgg",
		"ggVBwwwwwwwwBVgg",
		"ggVBwwwwwwwwBVgg",
		"ggVBwwwwwwvwBVgg",
		"ggVBwwwwwwwwBVgg",
		"ggVBwwwwwwwwBVgg",
		"ggVBwwwwwwwwBVgg",
		"ggVBwwvwwwwwBVgg",
		"ggVBwwwwwwwwBVgg",
		"ggVBwwwwwwwwBVgg",
		"ggVBwwwwwwvwBVgg",
		"ggVBwwwwwwwwBVgg",
		"ggVBwwwwwwwwBVgg",
		"ggVBwwwwwwwwBVgg",
		"ggVBwwvwwwwwBVgg",
		"ggVBwwwwwwwwBVgg",
		"ggVBwwwwwwwwBVgg",
		"ggVBwwwwwwvwBVgg",
		"ggVBwwwwwwwwBVgg",
		"ggVBwwwwwwwwBVgg",
		"ggVBwwwwwwwwBVgg",
		"ggVBwwvwwwwwBVgg",
		"ggVBwwwwwwwwBVgg",
		"ggVBwwwwwwwwBVgg",
		"ggVBwwwwwwvwBVgg",
		"ggVBwwwwwwwwBVgg",
		"ggVBwwwwwwwwBVgg",
		"ggVBwwwwwwwwBVgg",
		"ggVBwwvwwwwwBVgg",
		"ggVBwwwwwwwwBVgg",
		"ggVBwwwwwwwwBVgg",
		"ggVBwwwwwwvwBVgg",
		"ggVBwwwwwwwwBVgg",
		"ggVBwwwwwwwwBVgg",
		"ggVBwwwwwwwwBVgg",
		"ggVBBBBBBBBBBVgg",
		"VgVgVgVgVgVgVgVg",
		"gVgVgVgVgVgVgVgV",
		"FFFFFFFFFFFFFFFF",
		"KKKKKKKKKKKKKKKK",
	],
	"sky_lobby": [
		"KKKKKKKKKKKKKKKK",
		"VVxxxxxxxxxxxxVV",
		"VVxxxxxxLxxxxxVV",
		"VVxBBBBBBBBBBxVV",
		"VVxBwwwwwwwwBxVV",
		"VVxBwwvwwwwwBxVV",
		"VVxBwwwwwwwwBxVV",
		"VVxBwwwwwwwwBxVV",
		"VVxBwwwwwwvwBxVV",
		"VVxBwwwwwwwwBxVV",
		"VVxBBBBBBBBBBxVV",
		"VVxxxxxxxxxxxxVV",
		"VgVgVgVgVgVgVgVg",
		"gVgVgVgVgVgVgVgV",
		"FFFFFFFFFFFFFFFF",
		"KKKKKKKKKKKKKKKK",
	],
	"housekeeping": [
		"KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK",
		"TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT",
		"TeeeeeeeeeeeeeeTTeeeeeeeeeeeeeeT",
		"TTPPTPPTPPTTTTTTTTPPTPPTPPTPPTTT",
		"TTPPTPPTPPTTTTTTTTPPTPPTPPTPPTTT",
		"TeeeeeeeeeeeeeeTTeeeeeeeeeeeeeeT",
		"TTTTTTTTTTTTOTTTTTTTTTTTTTTTTTTT",
		"TTTTTTTTTTTTOTTTTTTKKKKKKKKKKTTT",
		"TTTTTTTTTTTTOTTTTTTKVVVVVVVVKTTT",
		"TTTTTTTTTTTTOTTTTTTKVVKKKKVVKTTT",
		"TTTTTTTTTTTTOTTTTTTKVKwwwwKVKTTT",
		"TTTKKKKKTTTTOTTTTTTKVKwwwwKVKTTT",
		"TTTKYYYKTTTPPPTTTTTKVVKKKKVVKTTT",
		"TTTKYYYKTTTPPPTTTTTKVVVVVVVVKTTT",
		"FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
		"KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK",
	],
	"restaurant": [
		"KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK",
		"NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN",
		"NNNNNQQQQQQNNNNNNNNBBBBBBBBBBNNNNNNBBBBBBBBBBNNN",
		"NNNNQQQQQQQQNNNNNNNBwwwwwwwwBNNNNNNBwwwwwwwwBNNN",
		"NNNNLLLLLLLLNNNNNNNBwwwvwwwwBNNNNNNBwwwvwwwwBNNN",
		"NNNNqqqqqqqqNNNNNNNBwwwwwwwwBNNNNNNBwwwwwwwwBNNN",
		"NNNNQQQQQQQQNNNNNNNBBBBBBBBBBNNNNNNBBBBBBBBBBNNN",
		"NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN",
		"NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN",
		"nnnnnnnnnnnnnnnNNNNNNNLLNNNNNNNNNNNNNNLLNNNNNNNN",
		"KKKKKKKKKKKKKKKNNNeNNPPPPPPNNeNNNNeNNPPPPPPNNeNN",
		"nnnnnnnnnnnnnnnNNeeeNeeeeeeNeeeNNeeeNeeeeeeNeeeN",
		"nnnnnnnnnnnnnnnNNNeNNNNeeNNNNeNNNNeNNNNeeNNNNeNN",
		"nnnnnnnnnnnnnnnNNNeNNNNeeNNNNeNNNNeNNNNeeNNNNeNN",
		"FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
		"KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK",
	],
	"recycling": [
		"KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK",
		"ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ",
		"ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ",
		"ZZZZZZzzzzZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ",
		"ZZZZZzZZZZzZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ",
		"ZZZZzZZZZZZzZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ",
		"ZZZZZZZZZZzZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ",
		"ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ",
		"ZKKKKKKZZKKKKKKZZKKKKKKZZKKKKKKZZKKKKKKZZKKKKKKZ",
		"ZKzzzzKZZKxxxxKZZKzzzzKZZKzzzzKZZKxxxxKZZKxxxxKZ",
		"ZKzwzzKZZKxwxxKZZKzwzzKZZKzwzzKZZKxwxxKZZKxwxxKZ",
		"ZKzzzzKZZKxxxxKZZKzzzzKZZKzzzzKZZKxxxxKZZKxxxxKZ",
		"ZKzzzzKZZKxxxxKZZKzzzzKZZKzzzzKZZKxxxxKZZKxxxxKZ",
		"ZKzzzzKZZKxxxxKZZKzzzzKZZKzzzzKZZKxxxxKZZKxxxxKZ",
		"FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
		"KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK",
	],
	"security": [
		"KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK",
		"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
		"AKKKKKKAKKKKKKAAAAAAAAAAAAAAAAAA",
		"AKmmmmKAKmmmmKAAAAAAAaaaaaAAAAAA",
		"AKmmmmKAKmmmmKAAAAAAaaKKaaaAAAAA",
		"AKKKKKKAKKKKKKAAAAAAaaaaaaaAAAAA",
		"AKKKKKKAKKKKKKAAAAAAAaaaaaAAAAAA",
		"AKmmmmKAKmmmmKAAAAAAAAaaaAAAAAAA",
		"AKmmmmKAKmmmmKAAAAAAAAAaAAAAAAAA",
		"AKKKKKKAKKKKKKAAAAAAAAAAAAAAAAAA",
		"AAAAAAAAAAAAAAAAAAAAAAAAAAAMMMAA",
		"GGGGGGGGGGGGGGGAGGGGGGGGGGGmmmGA",
		"GAAAAAAAAAAAAAGAGAAAAAAAAGAAAAGA",
		"GAAAAAAAAAAAAAGAGAAAAAAAAGAAAAGA",
		"FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
		"KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK",
	],
	"medical": [
		"KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK",
		"VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV",
		"VVVBBBBBBBBBBVVVVVVVVVVVVVVVVVVVVVVBBBBBBBBBBVVV",
		"VVVBwwwwwwwwBVVVVVVVVVXXXXVVVVVVVVVBwwwwwwwwBVVV",
		"VVVBwwwvwwwwBVVVVVVVVVXXXXVVVVVVVVVBwwwwvwwwBVVV",
		"VVVBwwwwwwwwBVVVVVVXXXXXXXXXXVVVVVVBwwwwwwwwBVVV",
		"VVVBBBBBBBBBBVVVVVVXXXXXXXXXXVVVVVVBBBBBBBBBBVVV",
		"VVVVVVVVVVVVVVVVVVVVVVXXXXVVVVVVVVVVVVVVVVVVVVVV",
		"VVVVVVVVVVVVVVVVVVVVVVXXXXVVVVVVVVVVVVVVVVVVVVVV",
		"VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV",
		"XXXXXXXXXXXXXVVVVVVVVVVVVVVVVVVVVPPPVVVVVVVVVVVV",
		"gggggggggggggVVVVVVVVVVVVVVVVVVVgggggggggggggggV",
		"gVVVVVVVVVVVgVVVVVVVVVVVVVVVVVVVgVVVVVVVVVVVVVgV",
		"gVVVVVVVVVVVgVVVVVVVVVVVVVVVVVVVgVVVVVVVVVVVVVgV",
		"FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
		"KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK",
	],
	"housing": [
		"KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK",
		"hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh",
		"hhhhhhhhhhhhhhhhhhBBBBBBBBBBBBhhhhBBBBBBBBBBBBhh",
		"hhhhhhhhhhhhhpphhhBwwwwwwvwwwBhhhhBwwwwwwvwwwBhh",
		"hhhhhhhhhhhhpppphhBwwwwwvwwwwBhhhhBwwwwwvwwwwBhh",
		"hhKKKKKhhhhhhpphhhBwwwwwwwwwwBhhhhBwwwwwwwwwwBhh",
		"hhKoooKhhhhhhhOhhhBBBBBBBBBBBBhhhhBBBBBBBBBBBBhh",
		"hhKoooKhhhhhhhOhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh",
		"hhKoooKhhhhhhhOhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh",
		"hhKoaoKhhhhhhhOhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh",
		"hhKoooKhhhhheeehhyyyyyyyyyyyyyyhePPPEEEEEEEEEEeh",
		"hhKoooKhhhhhheehyyyyyyyyyyyyyyyyePPPEEEEEEEEEEeh",
		"hhKoooKhhhhhhhhhyyyyyyyyyyyyyyyyeeeeeeeeeeeeeeeh",
		"hhKoooKhhhhhhhhhyhhhhhhhhhhhhhhyehhhhhhhhhhhhheh",
		"FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
		"KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK",
	],
}

# 建物の横幅（マス数）
static func tile_width(type: String) -> int:
	return TILES[type][0].length() / SIZE

# 建物の高さ（階数）
static func tile_height(type: String) -> int:
	return TILES[type].size() / SIZE

# 指定した建物の絵全体の画像（横 16×マス数、縦 16×階数）を作る
static func make_tile_image(type: String) -> Image:
	var rows: Array = TILES[type]
	var width: int = rows[0].length()
	var image := Image.create(width, rows.size(), false, Image.FORMAT_RGBA8)
	for y in rows.size():
		for x in width:
			var ch: String = rows[y][x]
			image.set_pixel(x, y, PALETTE.get(ch, Color.TRANSPARENT))
	return image

# タイルを columns × rows 個並べた画像（1枚の画像を複数タイルに分けているTileSetのソース用）
# 横に複数マスの建物は、左から順に絵の区画を並べる（列 x には区画 x % マス数）
static func make_atlas_image(type: String, columns: int, rows: int) -> Image:
	var sprite := make_tile_image(type)
	var width := tile_width(type)
	var atlas := Image.create(SIZE * columns, SIZE * rows, false, Image.FORMAT_RGBA8)
	for ty in rows:
		for tx in columns:
			var segment := tx % width
			atlas.blit_rect(sprite, Rect2i(segment * SIZE, 0, SIZE, SIZE), Vector2i(tx * SIZE, ty * SIZE))
	return atlas
